Step6 코드 리팩토링, carousel 재사용가능하게 수정
kakao-2021/fe-w23-shoppinghow pull request #37
Opened 2021-01-18 09:41 UTC by tjrdud123

- main.js, render.js 코드 정리
- carousel.js 재사용 가능하게 수정
- webpack, babel 학습

2021-01-18 13:39 UTC, gunhoflash requested changes
주석이 잘 적혀있어 이해하기 편했어요.
저도 주석을 많이 써야할 것 같습니다. :)

2021-01-18 13:39 UTC, gunhoflash commented on public/js/carousel.js
> +            overflow: hidden; margin: auto; position:relative`);
스타일은 나중에 따로 클래스나 함수로 만들어주시면 더 좋을 것 같아요!

2021-01-18 13:39 UTC, gunhoflash commented on public/js/carousel.js
> +        }, { once: true });
```
this.prevBtnDOM.addEventListener("click", this.prev, { once: true });
```
로 줄일 수 있을 것 같아요

2021-01-18 15:00 UTC, puba5 commented on public/js/carousel.js
> +        this.cnt = cnt; // 한번에 보여지는 요소의 개수
cnt라는 변수 이름이 직관적으로 이해하기 힘든 것 같아요.
그리고 자주 쓰이는 변수 같은데 생성자에 멤버 변수 선언을 해보는건 어떨까요?? this.cnt가 무슨 변수일까?하고 올라가보니까 없어서 보기 어려웠던 것 같아요.

2021-01-18 15:01 UTC, puba5 reviewed
첫 날부터 작업 많이 하셨네요. 저도 보고 배워야겠어요. 이번 주도 파이팅입니다!

2021-01-18 15:04 UTC, merged

2021-01-19 03:37 UTC, tjrdud123 commented on public/js/carousel.js
> +        }, { once: true });
this때문이었는데 오늘 얘기했던대로 고쳐볼게요!

2021-01-19 03:38 UTC, tjrdud123 commented on public/js/carousel.js
> +        this.cnt = cnt; // 한번에 보여지는 요소의 개수
그러네요 수정해보겠습니다!